easy_admin:
    design:
        menu:
          - label: 'Menu'
            icon: 'users'
            children: ['Product', 'Category', 'User']
    entities:
       - App\Entity\Product
       - App\Entity\Category
       - App\Entity\User
    