# config/packages/security.yaml
security:
    encoders:
      App\Entity\User:
        algorithm: bcrypt
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
