easy_admin:
    design:
        menu:
          - { entity : Category, label : Категория , permission : ROLE_USER1 }
    entities:
        Category:
            class: App\Entity\Category
            label: 'Список категорий'
            list:
                fields:
                    - { property: 'name', label : 'Название' }

