easy_admin:
    design:
        menu:
          - { entity : Product, label : Товары , permission : [ ROLE_USER1 ]}
    entities:
        Product:
            class: App\Entity\Product
            permissions:
            label: 'Список товаров'
            icon: users
            list:
                item_permission: [ ROLE_USER1 ]
                fields:
                    - { property: 'name', label : 'Название', permission: 'ROLE_ADMIN'}
                    - { property: 'price',  label : 'Цена' }
                    - { property: 'category_id', label : '# категории' }

                actions:
                    - { name: 'edit', label: 'Редактировать' }
                    - { name: 'show', label: 'Смотреть' }

            edit:
                item_permission: [ ROLE_USER1 ]
