easy_admin:
    design:
        menu:
          - { entity : User, label : Пользователи, permission : [ ROLE_USER1, ROLE_USER2, ROLE_USER3 ] }
    entities:
        User:
            class: App\Entity\User
            label: 'Список пользователей'
            icon: 'user'
            list:
                item_permission: [ ROLE_USER1, ROLE_USER2, ROLE_USER3 ]
                fields:
                    - { property: 'name', label : 'Имя' }
                    - { property: 'email',  label : 'email' }
                    - { property: 'rcollection', label : 'Роли'}
                    - { property: 'groups', label : 'Группы'}
                actions:
                    - { name: 'edit', label: 'Редактировать', permission : [ ROLE_USER1, ROLE_USER2 ] }
                    - { name: 'show', label: 'Смотреть', permission : [ ROLE_USER1 ] }
                    - { name: 'delete', label: 'Удалить', permission : [ ROLE_USER1 ]}

            edit:
                item_permission: [ ROLE_USER1 ]
                fields:
                    - { property: 'name', label : 'Имя' }
                    - { property: 'email',  label : 'email' }
                    - { property: 'rcollection', label : 'Роли'}
                    - { property: 'groups', label : 'Группы'}


            show:
                # item_permission: ['ROLE_USER1']
                fields:
                    - { property: 'name', label : 'Имя' }
                    - { property: 'email',  label : 'email' }
                    - { property: 'rcollection', label : 'Роли'}
                    - { property: 'groups', label : 'Группы'}

                actions:
                    - { name: '-edit' }
                    - { name: '-delete' }


